# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EditGameDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(347, 150)
        Dialog.setMinimumSize(QtCore.QSize(347, 150))
        Dialog.setMaximumSize(QtCore.QSize(347, 150))
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 11, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.lineEdit_title = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_title.setMinimumSize(QtCore.QSize(327, 25))
        self.lineEdit_title.setMaximumSize(QtCore.QSize(327, 25))
        self.lineEdit_title.setObjectName("lineEdit_title")
        self.verticalLayout.addWidget(self.lineEdit_title)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.comboBox_status = QtWidgets.QComboBox(Dialog)
        self.comboBox_status.setObjectName("comboBox_status")
        self.horizontalLayout_4.addWidget(self.comboBox_status)
        self.comboBox_console = QtWidgets.QComboBox(Dialog)
        self.comboBox_console.setObjectName("comboBox_console")
        self.horizontalLayout_4.addWidget(self.comboBox_console)
        self.comboBox_score = QtWidgets.QComboBox(Dialog)
        self.comboBox_score.setObjectName("comboBox_score")
        self.horizontalLayout_4.addWidget(self.comboBox_score)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem1 = QtWidgets.QSpacerItem(20, 12, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.button_cancel = QtWidgets.QPushButton(Dialog)
        self.button_cancel.setObjectName("button_cancel")
        self.horizontalLayout_3.addWidget(self.button_cancel)
        self.button_delete = QtWidgets.QPushButton(Dialog)
        self.button_delete.setObjectName("button_delete")
        self.horizontalLayout_3.addWidget(self.button_delete)
        self.button_update = QtWidgets.QPushButton(Dialog)
        self.button_update.setObjectName("button_update")
        self.horizontalLayout_3.addWidget(self.button_update)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.button_cancel.setText(_translate("Dialog", "Cancel"))
        self.button_delete.setText(_translate("Dialog", "Delete game"))
        self.button_update.setText(_translate("Dialog", "Update game"))
