# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(850, 420)
        MainWindow.setMinimumSize(QtCore.QSize(850, 420))
        MainWindow.setMaximumSize(QtCore.QSize(850, 420))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setObjectName("tableView")
        self.horizontalLayout.addWidget(self.tableView)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.button_add = QtWidgets.QPushButton(self.centralwidget)
        self.button_add.setMinimumSize(QtCore.QSize(200, 50))
        self.button_add.setMaximumSize(QtCore.QSize(200, 50))
        self.button_add.setObjectName("button_add")
        self.verticalLayout.addWidget(self.button_add)
        self.button_edit = QtWidgets.QPushButton(self.centralwidget)
        self.button_edit.setMinimumSize(QtCore.QSize(200, 50))
        self.button_edit.setMaximumSize(QtCore.QSize(200, 50))
        self.button_edit.setObjectName("button_edit")
        self.verticalLayout.addWidget(self.button_edit)
        self.button_consoles = QtWidgets.QPushButton(self.centralwidget)
        self.button_consoles.setMinimumSize(QtCore.QSize(200, 50))
        self.button_consoles.setMaximumSize(QtCore.QSize(200, 50))
        self.button_consoles.setObjectName("button_consoles")
        self.verticalLayout.addWidget(self.button_consoles)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.lineEdit_search = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_search.setMinimumSize(QtCore.QSize(200, 25))
        self.lineEdit_search.setMaximumSize(QtCore.QSize(200, 25))
        self.lineEdit_search.setInputMask("")
        self.lineEdit_search.setObjectName("lineEdit_search")
        self.verticalLayout.addWidget(self.lineEdit_search)
        self.button_clear = QtWidgets.QPushButton(self.centralwidget)
        self.button_clear.setMinimumSize(QtCore.QSize(200, 50))
        self.button_clear.setMaximumSize(QtCore.QSize(200, 50))
        self.button_clear.setObjectName("button_clear")
        self.verticalLayout.addWidget(self.button_clear)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout.setStretch(0, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 850, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_add.setText(_translate("MainWindow", "Add game"))
        self.button_edit.setText(_translate("MainWindow", "Edit selected game"))
        self.button_consoles.setText(_translate("MainWindow", "Consoles"))
        self.lineEdit_search.setPlaceholderText(_translate("MainWindow", "Seach game title"))
        self.button_clear.setText(_translate("MainWindow", "Clear search"))
